version: '3.1'

services:
    build:
      network: host
    wp_php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5555:80'
        volumes:
            - ./wordpress:/var/www/html

        # nom de serveur = wp_db
    wp_db: 
        image: 'mariadb'
        restart: always
        environment: 
        # user= root
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - ./data.sql:/docker-entrypoint-initdb.d/dump.sql

    wp_pma:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
